name: Test
on: [push]
jobs:
  sca:
    name: Sca
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
          args: -c .golangci.yml
